# Generated by Django 5.0.1 on 2024-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_studentmodel_email_studentmodel_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='upload_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
