# Generated by Django 5.0.1 on 2024-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_alter_studentmodel_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
