# Generated by Django 5.0.1 on 2024-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_alter_studentmodel_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='uploadfile',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
